package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/marshallford/terraform-provider-pfsense/pkg/pfsense"
)

type FirewallScheduleTimeRangeModel struct {
	Position         types.String `tfsdk:"position"`
	Month            types.String `tfsdk:"month"`
	Day              types.String `tfsdk:"day"`
	StartTime        types.String `tfsdk:"start_time"`
	StopTime         types.String `tfsdk:"stop_time"`
	RangeDescription types.String `tfsdk:"range_description"`
}

func (FirewallScheduleTimeRangeModel) descriptions() map[string]attrDescription {
	return map[string]attrDescription{
		"position": {
			Description: "Comma separated list of weekday numbers for a weekly recurring range, where Monday is 1 and Sunday is 7 (e.g. '1,2,3,4,5' for weekdays). Mutually exclusive with month/day.",
		},
		"month": {
			Description: "Comma separated list of month numbers (1-12) for a specific calendar range, parallel to day. Mutually exclusive with position.",
		},
		"day": {
			Description: "Comma separated list of day-of-month numbers (1-31) for a specific calendar range, parallel to month. Mutually exclusive with position.",
		},
		"start_time": {
			Description: "Start time in 'H:MM' format (e.g. '0:00'). A full day is '0:00' to '23:59'. Minutes must be one of 00, 15, 30, 45 or 59.",
		},
		"stop_time": {
			Description: "Stop time in 'H:MM' format (e.g. '23:59'). A full day is '0:00' to '23:59'. Minutes must be one of 00, 15, 30, 45 or 59.",
		},
		"range_description": {
			Description: descriptionDescription,
		},
	}
}

func (FirewallScheduleTimeRangeModel) AttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"position":          types.StringType,
		"month":             types.StringType,
		"day":               types.StringType,
		"start_time":        types.StringType,
		"stop_time":         types.StringType,
		"range_description": types.StringType,
	}
}

func (m *FirewallScheduleTimeRangeModel) Set(_ context.Context, tr pfsense.ScheduleTimeRange) diag.Diagnostics {
	var diags diag.Diagnostics

	if tr.Position != "" {
		m.Position = types.StringValue(tr.Position)
	} else {
		m.Position = types.StringNull()
	}

	if tr.Month != "" {
		m.Month = types.StringValue(tr.Month)
	} else {
		m.Month = types.StringNull()
	}

	if tr.Day != "" {
		m.Day = types.StringValue(tr.Day)
	} else {
		m.Day = types.StringNull()
	}

	m.StartTime = types.StringValue(tr.StartTime)
	m.StopTime = types.StringValue(tr.StopTime)

	if tr.RangeDescription != "" {
		m.RangeDescription = types.StringValue(tr.RangeDescription)
	} else {
		m.RangeDescription = types.StringNull()
	}

	return diags
}

func (m FirewallScheduleTimeRangeModel) Value(_ context.Context, tr *pfsense.ScheduleTimeRange) diag.Diagnostics {
	var diags diag.Diagnostics

	if !m.Position.IsNull() {
		tr.Position = m.Position.ValueString()
	}

	if !m.Month.IsNull() {
		tr.Month = m.Month.ValueString()
	}

	if !m.Day.IsNull() {
		tr.Day = m.Day.ValueString()
	}

	tr.StartTime = m.StartTime.ValueString()
	tr.StopTime = m.StopTime.ValueString()

	if !m.RangeDescription.IsNull() {
		tr.RangeDescription = m.RangeDescription.ValueString()
	}

	return diags
}

type FirewallScheduleModel struct {
	Name        types.String `tfsdk:"name"`
	Description types.String `tfsdk:"description"`
	TimeRanges  types.List   `tfsdk:"time_range"`
	Label       types.String `tfsdk:"label"`
}

func (FirewallScheduleModel) descriptions() map[string]attrDescription {
	return map[string]attrDescription{
		"name": {
			Description: "Name of the schedule, used as the unique identifier. May only consist of the characters a-z, A-Z, 0-9 and _, and may not be 'LAN' or 'WAN'.",
		},
		"description": {
			Description: descriptionDescription,
		},
		"time_range": {
			Description: "List of time ranges during which the schedule is active. At least one is required.",
		},
		"label": {
			Description: "Internal label automatically generated by pfSense to identify the schedule.",
		},
	}
}

func (FirewallScheduleModel) AttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"name":        types.StringType,
		"description": types.StringType,
		"time_range":  types.ListType{ElemType: types.ObjectType{AttrTypes: FirewallScheduleTimeRangeModel{}.AttrTypes()}},
		"label":       types.StringType,
	}
}

func (m *FirewallScheduleModel) Set(ctx context.Context, s pfsense.Schedule) diag.Diagnostics {
	var diags diag.Diagnostics

	m.Name = types.StringValue(s.Name)

	if s.Description != "" {
		m.Description = types.StringValue(s.Description)
	} else {
		m.Description = types.StringNull()
	}

	m.Label = types.StringValue(s.Label)

	rangeModels := []FirewallScheduleTimeRangeModel{}
	for _, tr := range s.TimeRanges {
		var rangeModel FirewallScheduleTimeRangeModel
		diags.Append(rangeModel.Set(ctx, tr)...)
		rangeModels = append(rangeModels, rangeModel)
	}

	rangesValue, newDiags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: FirewallScheduleTimeRangeModel{}.AttrTypes()}, rangeModels)
	diags.Append(newDiags...)
	m.TimeRanges = rangesValue

	return diags
}

func (m FirewallScheduleModel) Value(ctx context.Context, s *pfsense.Schedule) diag.Diagnostics {
	var diags diag.Diagnostics

	addPathError(&diags, path.Root("name"), "Name cannot be parsed", s.SetName(m.Name.ValueString()))

	if !m.Description.IsNull() {
		addPathError(&diags, path.Root("description"), "Description cannot be parsed", s.SetDescription(m.Description.ValueString()))
	}

	var rangeModels []FirewallScheduleTimeRangeModel
	if !m.TimeRanges.IsNull() {
		diags.Append(m.TimeRanges.ElementsAs(ctx, &rangeModels, false)...)
	}

	ranges := make([]pfsense.ScheduleTimeRange, 0, len(rangeModels))
	for _, rangeModel := range rangeModels {
		var tr pfsense.ScheduleTimeRange
		diags.Append(rangeModel.Value(ctx, &tr)...)
		ranges = append(ranges, tr)
	}

	addPathError(&diags, path.Root("time_range"), "Time ranges cannot be parsed", s.SetTimeRanges(ranges))

	return diags
}
