package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/marshallford/terraform-provider-pfsense/pkg/pfsense"
)

// SystemAdvancedFirewallModel represents the Terraform model for system advanced firewall & NAT settings.
type SystemAdvancedFirewallModel struct {
	// Packet Processing
	ScrubNoDF           types.Bool   `tfsdk:"scrub_no_df"`
	ScrubRNID           types.Bool   `tfsdk:"scrub_random_id"`
	Optimization        types.String `tfsdk:"firewall_optimization"`
	DisableScrub        types.Bool   `tfsdk:"disable_scrub"`
	AdaptiveStart       types.Int64  `tfsdk:"adaptive_start"`
	AdaptiveEnd         types.Int64  `tfsdk:"adaptive_end"`
	MaximumStates       types.Int64  `tfsdk:"maximum_states"`
	MaximumTableEntries types.Int64  `tfsdk:"maximum_table_entries"`
	MaximumFragments    types.Int64  `tfsdk:"maximum_fragment_entries"`

	// VPN Packet Processing
	VPNScrubNoDF          types.Bool  `tfsdk:"vpn_scrub_no_df"`
	VPNFragmentReassemble types.Bool  `tfsdk:"vpn_fragment_reassemble"`
	MaxMSSEnable          types.Bool  `tfsdk:"max_mss_enable"`
	MaxMSS                types.Int64 `tfsdk:"max_mss"`

	// Advanced Options
	DisableFirewall        types.Bool  `tfsdk:"disable_firewall"`
	BypassStaticRoutes     types.Bool  `tfsdk:"bypass_static_routes"`
	DisableVPNRules        types.Bool  `tfsdk:"disable_vpn_rules"`
	DisableReplyTo         types.Bool  `tfsdk:"disable_reply_to"`
	DisableNegate          types.Bool  `tfsdk:"disable_negate"`
	NoAPIPA                types.Bool  `tfsdk:"no_apipa_block"`
	AliasesResolveInterval types.Int64 `tfsdk:"aliases_resolve_interval"`
	CheckAliasesURLCert    types.Bool  `tfsdk:"check_aliases_url_cert"`

	// Bogon Networks
	BogonsInterval types.String `tfsdk:"bogons_update_interval"`

	// NAT
	NATReflection             types.String `tfsdk:"nat_reflection_mode"`
	ReflectionTimeout         types.Int64  `tfsdk:"nat_reflection_timeout"`
	EnableBINATReflection     types.Bool   `tfsdk:"enable_binat_reflection"`
	EnableNATReflectionHelper types.Bool   `tfsdk:"enable_nat_reflection_helper"`
	TFTPInterface             types.String `tfsdk:"tftp_proxy_interfaces"`

	// State Timeouts
	TCPFirstTimeout       types.Int64 `tfsdk:"tcp_first_timeout"`
	TCPOpeningTimeout     types.Int64 `tfsdk:"tcp_opening_timeout"`
	TCPEstablishedTimeout types.Int64 `tfsdk:"tcp_established_timeout"`
	TCPClosingTimeout     types.Int64 `tfsdk:"tcp_closing_timeout"`
	TCPFinWaitTimeout     types.Int64 `tfsdk:"tcp_fin_wait_timeout"`
	TCPClosedTimeout      types.Int64 `tfsdk:"tcp_closed_timeout"`
	TCPTSDiffTimeout      types.Int64 `tfsdk:"tcp_tsdiff_timeout"`
	UDPFirstTimeout       types.Int64 `tfsdk:"udp_first_timeout"`
	UDPSingleTimeout      types.Int64 `tfsdk:"udp_single_timeout"`
	UDPMultipleTimeout    types.Int64 `tfsdk:"udp_multiple_timeout"`
	ICMPFirstTimeout      types.Int64 `tfsdk:"icmp_first_timeout"`
	ICMPErrorTimeout      types.Int64 `tfsdk:"icmp_error_timeout"`
	OtherFirstTimeout     types.Int64 `tfsdk:"other_first_timeout"`
	OtherSingleTimeout    types.Int64 `tfsdk:"other_single_timeout"`
	OtherMultipleTimeout  types.Int64 `tfsdk:"other_multiple_timeout"`
}

func (SystemAdvancedFirewallModel) descriptions() map[string]attrDescription {
	return map[string]attrDescription{
		"scrub_no_df": {
			Description: "Clear the IP Do-Not-Fragment bit from IPv4 packets matching scrub rules.",
		},
		"scrub_random_id": {
			Description: "Replace the IP identification field with random values to compensate for predictable values generated by many hosts.",
		},
		"firewall_optimization": {
			Description:         fmt.Sprintf("Firewall optimization algorithm. Options: %s. Defaults to '%s'.", wrapElementsJoin(pfsense.AdvancedFirewall{}.OptimizationOptions(), "'"), pfsense.DefaultAdvancedFirewallOptimization),
			MarkdownDescription: fmt.Sprintf("Firewall optimization algorithm. Options: %s. Defaults to `%s`.", wrapElementsJoin(pfsense.AdvancedFirewall{}.OptimizationOptions(), "`"), pfsense.DefaultAdvancedFirewallOptimization),
		},
		"disable_scrub": {
			Description: "Disable all packet normalization (scrub). Disabling can cause problems and is not recommended.",
		},
		"adaptive_start": {
			Description: "Adaptive Firewall States start value. When the number of state entries exceeds this value, adaptive scaling begins. Set to 0 for the pfSense default (60% of maximum states).",
		},
		"adaptive_end": {
			Description: "Adaptive Firewall States end value. When reaching this number of state entries, all timeout values become zero, effectively purging all state entries immediately. Set to 0 for the pfSense default (120% of maximum states).",
		},
		"maximum_states": {
			Description: "Maximum number of firewall state table entries. Set to 0 for the system default.",
		},
		"maximum_table_entries": {
			Description: "Maximum number of table entries for systems such as aliases, sshguard, snort, etc. Set to 0 for the system default.",
		},
		"maximum_fragment_entries": {
			Description: "Maximum number of packet fragments to reassemble. Set to 0 for the default (5000).",
		},
		"vpn_scrub_no_df": {
			Description: "Clear the IP Do-Not-Fragment bit from IPv4 packets passing through VPN tunnels.",
		},
		"vpn_fragment_reassemble": {
			Description: "Enable reassembly of fragmented VPN packets before processing.",
		},
		"max_mss_enable": {
			Description: "Enable MSS clamping on VPN traffic.",
		},
		"max_mss": {
			Description: fmt.Sprintf("Maximum MSS value for VPN traffic (range 576-65535). Defaults to '%d'. Only applicable when max_mss_enable is true.", pfsense.DefaultAdvancedFirewallMaxMSS),
		},
		"disable_firewall": {
			Description: "Disable all packet filtering. WARNING: This converts pfSense into a routing-only platform.",
		},
		"bypass_static_routes": {
			Description: "Bypass firewall rules for traffic on the same interface. Traffic that enters and leaves through the same interface is not checked by the firewall.",
		},
		"disable_vpn_rules": {
			Description: "Disable all auto-added VPN rules.",
		},
		"disable_reply_to": {
			Description: "Disable reply-to on WAN rules. This is useful for multi-WAN when using bridge interfaces.",
		},
		"disable_negate": {
			Description: "Disable automatic negation of private network rules when the network matches an interface subnet.",
		},
		"no_apipa_block": {
			Description: "Allow APIPA (Automatic Private IP Addressing) traffic (169.254.0.0/16).",
		},
		"aliases_resolve_interval": {
			Description: "Interval in seconds for resolving hostnames in aliases. Set to 0 for the default (300 seconds).",
		},
		"check_aliases_url_cert": {
			Description: "Verify HTTPS certificates when downloading URL table alias content.",
		},
		"bogons_update_interval": {
			Description:         fmt.Sprintf("Update frequency for the bogon networks lists. Options: %s. Defaults to '%s'.", wrapElementsJoin(pfsense.AdvancedFirewall{}.BogonsIntervalOptions(), "'"), pfsense.DefaultAdvancedFirewallBogonsInterval),
			MarkdownDescription: fmt.Sprintf("Update frequency for the bogon networks lists. Options: %s. Defaults to `%s`.", wrapElementsJoin(pfsense.AdvancedFirewall{}.BogonsIntervalOptions(), "`"), pfsense.DefaultAdvancedFirewallBogonsInterval),
		},
		"nat_reflection_mode": {
			Description:         fmt.Sprintf("NAT reflection mode for port forwards. Options: %s. Defaults to '%s'.", wrapElementsJoin(pfsense.AdvancedFirewall{}.NATReflectionOptions(), "'"), pfsense.DefaultAdvancedFirewallNATReflection),
			MarkdownDescription: fmt.Sprintf("NAT reflection mode for port forwards. Options: %s. Defaults to `%s`.", wrapElementsJoin(pfsense.AdvancedFirewall{}.NATReflectionOptions(), "`"), pfsense.DefaultAdvancedFirewallNATReflection),
		},
		"nat_reflection_timeout": {
			Description: fmt.Sprintf("Timeout in seconds for NAT reflection connections (proxy mode only). Set to 0 for the default (%d).", pfsense.DefaultAdvancedFirewallReflectionTimeout),
		},
		"enable_binat_reflection": {
			Description: "Enable NAT reflection for 1:1 NAT rules.",
		},
		"enable_nat_reflection_helper": {
			Description: "Enable automatic creation of outbound NAT rules to assist with NAT reflection.",
		},
		"tftp_proxy_interfaces": {
			Description: "Comma-separated list of interfaces where the TFTP proxy helper should operate.",
		},
		"tcp_first_timeout": {
			Description: "State timeout in seconds for the first TCP packet. Set to 0 for the pfSense default.",
		},
		"tcp_opening_timeout": {
			Description: "State timeout in seconds for TCP connections that have not yet completed the handshake. Set to 0 for the pfSense default.",
		},
		"tcp_established_timeout": {
			Description: "State timeout in seconds for established TCP connections. Set to 0 for the pfSense default.",
		},
		"tcp_closing_timeout": {
			Description: "State timeout in seconds for TCP FIN-WAIT and CLOSE-WAIT states. Set to 0 for the pfSense default.",
		},
		"tcp_fin_wait_timeout": {
			Description: "State timeout in seconds for TCP FIN-WAIT states after both sides have exchanged FIN. Set to 0 for the pfSense default.",
		},
		"tcp_closed_timeout": {
			Description: "State timeout in seconds for TCP RST states. Set to 0 for the pfSense default.",
		},
		"tcp_tsdiff_timeout": {
			Description: "State timeout in seconds for TCP TSDIFF (timestamp difference). Set to 0 for the pfSense default.",
		},
		"udp_first_timeout": {
			Description: "State timeout in seconds for the first UDP packet. Set to 0 for the pfSense default.",
		},
		"udp_single_timeout": {
			Description: "State timeout in seconds for UDP connections with only a single packet. Set to 0 for the pfSense default.",
		},
		"udp_multiple_timeout": {
			Description: "State timeout in seconds for UDP connections with multiple packets. Set to 0 for the pfSense default.",
		},
		"icmp_first_timeout": {
			Description: "State timeout in seconds for the first ICMP packet. Set to 0 for the pfSense default.",
		},
		"icmp_error_timeout": {
			Description: "State timeout in seconds for ICMP error messages. Set to 0 for the pfSense default.",
		},
		"other_first_timeout": {
			Description: "State timeout in seconds for the first packet of protocols other than TCP/UDP/ICMP. Set to 0 for the pfSense default.",
		},
		"other_single_timeout": {
			Description: "State timeout in seconds for other protocol connections with only a single packet. Set to 0 for the pfSense default.",
		},
		"other_multiple_timeout": {
			Description: "State timeout in seconds for other protocol connections with multiple packets. Set to 0 for the pfSense default.",
		},
	}
}

func (SystemAdvancedFirewallModel) AttrTypes() map[string]attr.Type {
	return map[string]attr.Type{
		"scrub_no_df":                  types.BoolType,
		"scrub_random_id":              types.BoolType,
		"firewall_optimization":        types.StringType,
		"disable_scrub":                types.BoolType,
		"adaptive_start":               types.Int64Type,
		"adaptive_end":                 types.Int64Type,
		"maximum_states":               types.Int64Type,
		"maximum_table_entries":        types.Int64Type,
		"maximum_fragment_entries":     types.Int64Type,
		"vpn_scrub_no_df":              types.BoolType,
		"vpn_fragment_reassemble":      types.BoolType,
		"max_mss_enable":               types.BoolType,
		"max_mss":                      types.Int64Type,
		"disable_firewall":             types.BoolType,
		"bypass_static_routes":         types.BoolType,
		"disable_vpn_rules":            types.BoolType,
		"disable_reply_to":             types.BoolType,
		"disable_negate":               types.BoolType,
		"no_apipa_block":               types.BoolType,
		"aliases_resolve_interval":     types.Int64Type,
		"check_aliases_url_cert":       types.BoolType,
		"bogons_update_interval":       types.StringType,
		"nat_reflection_mode":          types.StringType,
		"nat_reflection_timeout":       types.Int64Type,
		"enable_binat_reflection":      types.BoolType,
		"enable_nat_reflection_helper": types.BoolType,
		"tftp_proxy_interfaces":        types.StringType,
		"tcp_first_timeout":            types.Int64Type,
		"tcp_opening_timeout":          types.Int64Type,
		"tcp_established_timeout":      types.Int64Type,
		"tcp_closing_timeout":          types.Int64Type,
		"tcp_fin_wait_timeout":         types.Int64Type,
		"tcp_closed_timeout":           types.Int64Type,
		"tcp_tsdiff_timeout":           types.Int64Type,
		"udp_first_timeout":            types.Int64Type,
		"udp_single_timeout":           types.Int64Type,
		"udp_multiple_timeout":         types.Int64Type,
		"icmp_first_timeout":           types.Int64Type,
		"icmp_error_timeout":           types.Int64Type,
		"other_first_timeout":          types.Int64Type,
		"other_single_timeout":         types.Int64Type,
		"other_multiple_timeout":       types.Int64Type,
	}
}

func (m *SystemAdvancedFirewallModel) Set(_ context.Context, a pfsense.AdvancedFirewall) diag.Diagnostics {
	var diags diag.Diagnostics

	// Packet Processing
	m.ScrubNoDF = types.BoolValue(a.ScrubNoDF)
	m.ScrubRNID = types.BoolValue(a.ScrubRNID)
	m.Optimization = types.StringValue(a.Optimization)
	m.DisableScrub = types.BoolValue(a.DisableScrub)
	m.AdaptiveStart = types.Int64Value(int64(a.AdaptiveStart))
	m.AdaptiveEnd = types.Int64Value(int64(a.AdaptiveEnd))
	m.MaximumStates = types.Int64Value(int64(a.MaximumStates))
	m.MaximumTableEntries = types.Int64Value(int64(a.MaximumTableEntries))
	m.MaximumFragments = types.Int64Value(int64(a.MaximumFragments))

	// VPN Packet Processing
	m.VPNScrubNoDF = types.BoolValue(a.VPNScrubNoDF)
	m.VPNFragmentReassemble = types.BoolValue(a.VPNFragmentReassemble)
	m.MaxMSSEnable = types.BoolValue(a.MaxMSSEnable)
	m.MaxMSS = types.Int64Value(int64(a.MaxMSS))

	// Advanced Options
	m.DisableFirewall = types.BoolValue(a.DisableFirewall)
	m.BypassStaticRoutes = types.BoolValue(a.BypassStaticRoutes)
	m.DisableVPNRules = types.BoolValue(a.DisableVPNRules)
	m.DisableReplyTo = types.BoolValue(a.DisableReplyTo)
	m.DisableNegate = types.BoolValue(a.DisableNegate)
	m.NoAPIPA = types.BoolValue(a.NoAPIPA)
	m.AliasesResolveInterval = types.Int64Value(int64(a.AliasesResolveInterval))
	m.CheckAliasesURLCert = types.BoolValue(a.CheckAliasesURLCert)

	// Bogon Networks
	m.BogonsInterval = types.StringValue(a.BogonsInterval)

	// NAT
	m.NATReflection = types.StringValue(a.NATReflection)
	m.ReflectionTimeout = types.Int64Value(int64(a.ReflectionTimeout))
	m.EnableBINATReflection = types.BoolValue(a.EnableBINATReflection)
	m.EnableNATReflectionHelper = types.BoolValue(a.EnableNATReflectionHelper)

	if a.TFTPInterface != "" {
		m.TFTPInterface = types.StringValue(a.TFTPInterface)
	} else {
		m.TFTPInterface = types.StringNull()
	}

	// State Timeouts
	m.TCPFirstTimeout = types.Int64Value(int64(a.TCPFirstTimeout))
	m.TCPOpeningTimeout = types.Int64Value(int64(a.TCPOpeningTimeout))
	m.TCPEstablishedTimeout = types.Int64Value(int64(a.TCPEstablishedTimeout))
	m.TCPClosingTimeout = types.Int64Value(int64(a.TCPClosingTimeout))
	m.TCPFinWaitTimeout = types.Int64Value(int64(a.TCPFinWaitTimeout))
	m.TCPClosedTimeout = types.Int64Value(int64(a.TCPClosedTimeout))
	m.TCPTSDiffTimeout = types.Int64Value(int64(a.TCPTSDiffTimeout))
	m.UDPFirstTimeout = types.Int64Value(int64(a.UDPFirstTimeout))
	m.UDPSingleTimeout = types.Int64Value(int64(a.UDPSingleTimeout))
	m.UDPMultipleTimeout = types.Int64Value(int64(a.UDPMultipleTimeout))
	m.ICMPFirstTimeout = types.Int64Value(int64(a.ICMPFirstTimeout))
	m.ICMPErrorTimeout = types.Int64Value(int64(a.ICMPErrorTimeout))
	m.OtherFirstTimeout = types.Int64Value(int64(a.OtherFirstTimeout))
	m.OtherSingleTimeout = types.Int64Value(int64(a.OtherSingleTimeout))
	m.OtherMultipleTimeout = types.Int64Value(int64(a.OtherMultipleTimeout))

	return diags
}

func (m SystemAdvancedFirewallModel) Value(_ context.Context, a *pfsense.AdvancedFirewall) diag.Diagnostics {
	var diags diag.Diagnostics

	// Packet Processing
	a.ScrubNoDF = m.ScrubNoDF.ValueBool()
	a.ScrubRNID = m.ScrubRNID.ValueBool()

	addPathError(
		&diags,
		path.Root("firewall_optimization"),
		"Firewall optimization cannot be parsed",
		a.SetOptimization(m.Optimization.ValueString()),
	)

	a.DisableScrub = m.DisableScrub.ValueBool()
	a.AdaptiveStart = int(m.AdaptiveStart.ValueInt64())
	a.AdaptiveEnd = int(m.AdaptiveEnd.ValueInt64())
	a.MaximumStates = int(m.MaximumStates.ValueInt64())
	a.MaximumTableEntries = int(m.MaximumTableEntries.ValueInt64())
	a.MaximumFragments = int(m.MaximumFragments.ValueInt64())

	// VPN Packet Processing
	a.VPNScrubNoDF = m.VPNScrubNoDF.ValueBool()
	a.VPNFragmentReassemble = m.VPNFragmentReassemble.ValueBool()
	a.MaxMSSEnable = m.MaxMSSEnable.ValueBool()

	if a.MaxMSSEnable && !m.MaxMSS.IsNull() && m.MaxMSS.ValueInt64() > 0 {
		addPathError(
			&diags,
			path.Root("max_mss"),
			"Max MSS cannot be parsed",
			a.SetMaxMSS(int(m.MaxMSS.ValueInt64())),
		)
	} else {
		a.MaxMSS = int(m.MaxMSS.ValueInt64())
	}

	// Advanced Options
	a.DisableFirewall = m.DisableFirewall.ValueBool()
	a.BypassStaticRoutes = m.BypassStaticRoutes.ValueBool()
	a.DisableVPNRules = m.DisableVPNRules.ValueBool()
	a.DisableReplyTo = m.DisableReplyTo.ValueBool()
	a.DisableNegate = m.DisableNegate.ValueBool()
	a.NoAPIPA = m.NoAPIPA.ValueBool()
	a.AliasesResolveInterval = int(m.AliasesResolveInterval.ValueInt64())
	a.CheckAliasesURLCert = m.CheckAliasesURLCert.ValueBool()

	// Bogon Networks
	addPathError(
		&diags,
		path.Root("bogons_update_interval"),
		"Bogons interval cannot be parsed",
		a.SetBogonsInterval(m.BogonsInterval.ValueString()),
	)

	// NAT
	addPathError(
		&diags,
		path.Root("nat_reflection_mode"),
		"NAT reflection mode cannot be parsed",
		a.SetNATReflection(m.NATReflection.ValueString()),
	)

	a.ReflectionTimeout = int(m.ReflectionTimeout.ValueInt64())
	a.EnableBINATReflection = m.EnableBINATReflection.ValueBool()
	a.EnableNATReflectionHelper = m.EnableNATReflectionHelper.ValueBool()

	if !m.TFTPInterface.IsNull() {
		a.TFTPInterface = m.TFTPInterface.ValueString()
	}

	// State Timeouts
	a.TCPFirstTimeout = int(m.TCPFirstTimeout.ValueInt64())
	a.TCPOpeningTimeout = int(m.TCPOpeningTimeout.ValueInt64())
	a.TCPEstablishedTimeout = int(m.TCPEstablishedTimeout.ValueInt64())
	a.TCPClosingTimeout = int(m.TCPClosingTimeout.ValueInt64())
	a.TCPFinWaitTimeout = int(m.TCPFinWaitTimeout.ValueInt64())
	a.TCPClosedTimeout = int(m.TCPClosedTimeout.ValueInt64())
	a.TCPTSDiffTimeout = int(m.TCPTSDiffTimeout.ValueInt64())
	a.UDPFirstTimeout = int(m.UDPFirstTimeout.ValueInt64())
	a.UDPSingleTimeout = int(m.UDPSingleTimeout.ValueInt64())
	a.UDPMultipleTimeout = int(m.UDPMultipleTimeout.ValueInt64())
	a.ICMPFirstTimeout = int(m.ICMPFirstTimeout.ValueInt64())
	a.ICMPErrorTimeout = int(m.ICMPErrorTimeout.ValueInt64())
	a.OtherFirstTimeout = int(m.OtherFirstTimeout.ValueInt64())
	a.OtherSingleTimeout = int(m.OtherSingleTimeout.ValueInt64())
	a.OtherMultipleTimeout = int(m.OtherMultipleTimeout.ValueInt64())

	return diags
}
